npsp/protected/controllers/SiteController.php
<?php
class SiteController extends Controller {
	const ARCHIVES = 'archives';
	/**
	 * Declares class-based actions.
	 */
	public function actions() {
		return array(
		);
	}

	public function filters()  {
		return array(
			'seo -poll',
			'insertEmail',
		);
	}

	public function filterSeo($filterChain) {
		$seoImpl = new SeoImpl;
		$seoImpl->build();
		$this->pageTitle = SeoImpl::$pageTitle;
		$filterChain->run();
	}

	public function filterInsertEmail($filterChain) {
		/** @var $cs  CHttpRequest */
		$cs = Yii::app()->request;
		$email = $cs->getPost('email');
		if(isset($email) && !empty($email)) {
			$emailModel = new EmailExtend;
			$emailModel->email = $email;
			$emailModel->status = StatusBehavior::STATUS_ACTIV;
			$emailModel->save();
		}
		$filterChain->run();
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex() {
		$homeModels = HomeExtend::model('HomeExtend')->frontEnd()->findAll();

        if (isset($_POST["mail"])) {
            if (!empty($_POST["mail"]) && !empty($_POST["object"]) && !empty($_POST["message"]) && !empty($_POST["tel"]) )
            {
                $from = $_POST["mail"]; // sender
                $subject = $_POST["object"];
                $message = 'Nom : '.$_POST["name"];
                $message .= '<br/>Adresse mail : '.$_POST["mail"];
                $message .= '<br/>Téléphone : '.$_POST["tel"];
                $message .= '<br/>Message : '.$_POST["message"];
                // message lines should not exceed 70 characters (PHP rule), so wrap it
                $message = wodwrap($message, 70);
                // send mail

                mail("webmaster@npsp-ci.com",$subject,$message,"From: $from\n");
            }
        }
		
		/*poll_form is not defined in the code ... */
        if (isset($_POST['PollUserAnswerExtend']) && !empty($_POST['PollUserAnswerExtend'])) {
            $valid = true;

            $items=$_POST['PollUserAnswerExtend'];
           foreach ($items as $i => $value)
           {
               $pollUserAnswer = new PollUserAnswerExtend();
                   $pollUserAnswer->poll_answer_id = $value['poll_answer_id'];
                   $pollUserAnswer->status =1;
                   $pollUserAnswer->answer =1;
                   $valid=$pollUserAnswer->validate() && $valid;

                   $pollUserAnswer->save();
           }
		}

        $this->render('index', array(
			'homeModels' => $homeModels,
		));
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError() {
		if($error=Yii::app()->errorHandler->error) {
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	public function actionPartner() {
		$partnerModels = PartnerExtend::model('PartnerExtend')->frontEnd()->findAll();
		$this->render('partner', array(
			'partnerModels' => $partnerModels,
		));
	}

	
	public function actionNewsAll() {
		$page_size = 12;
		$criteria = new CDbCriteria(array(
			"condition" => "t.status = '".StatusBehavior::STATUS_ACTIV."'",
			"order" => "t.create_time DESC",
		));

		$items_count = NewsExtend::model('NewsExtend')->count($criteria);
		$pages = new CPagination($items_count);
		$pages->setPageSize($page_size);
		$pages->applyLimit($criteria);
		$newsModels = NewsExtend::model('NewsExtend')->findAll($criteria);

		if (!empty($newsModels)) {
			$this->render('news_all', array(
				'newsModels' => $newsModels,
				'pages'         =>  $pages,
				'page_size'     =>  $page_size,
				'items_count'   =>  $items_count,
			));
		} else {
			$this->redirect(array('site/index'));
		}
	}
	
	public function actionPublicationAll() {
		$page_size = 12;
		$criteria = new CDbCriteria(array(
			"condition" => "t.status = '".StatusBehavior::STATUS_ACTIV."'",
			"order" => "t.create_time DESC",
		));

		$items_count = PublicationExtend::model('PublicationExtend')->count($criteria);
		$pages = new CPagination($items_count);
		$pages->setPageSize($page_size);
		$pages->applyLimit($criteria);
		$pModels = PublicationExtend::model('PublicationExtend')->findAll($criteria);

		if (!empty($pModels)) {
			$this->render('publication_all', array(
				'pModels' => $pModels,
				'pages'         =>  $pages,
				'page_size'     =>  $page_size,
				'items_count'   =>  $items_count,
			));
		} else {
			$this->redirect(array('site/index'));
		}
	}

	public function toBeDeleted() {

	}

	public function actionNews() {
		$newsModels = NewsExtend::model('NewsExtend')->findAll(array(
            "condition" => "t.status = '".StatusBehavior::STATUS_ACTIV."'",
            "order" => "t.create_time DESC",
            'limit' => 3,
			));

		if(isset($_GET['id']) && !empty($_GET['id'])){
            $id = $_GET['id'];
            $currnewsModel = NewsExtend::model('NewsExtend')->frontEnd()->find(array( "condition" => "t.id = '".$id."'",));
        } else {
            $currnewsModel = NewsExtend::model('NewsExtend')->frontEnd()->find(array(
                "condition" => "t.status = '".StatusBehavior::STATUS_ACTIV."'",
                "order" => "t.create_time DESC",
                "limit" => 1,));
        }

		if (!empty($currnewsModel)) {
			$this->render('news', array(
				'newsModels' => $newsModels,
				'currentnews' => $currnewsModel,
			));
		} else {
			$this->redirect(array('site/index'));
		}
	}

	private function commonLogic($className, $title, $extension = 'Extend') {
		$fullClass = $className.$extension;
		$objectModels = $fullClass::model($fullClass)->frontEnd()->findAll();

        if(isset($_GET['id']) && !empty($_GET['id'])){
            $id = $_GET['id'];
            $currObjectModel = $fullClass::model($fullClass)->frontEnd()->find(array( "condition" => "t.id = '".$id."'",));
        } else {
            $currObjectModel = $fullClass::model($fullClass)->frontEnd()->find(array(
                "condition" => "t.status = '".StatusBehavior::STATUS_ACTIV."'",
                "order" => "t.create_time DESC",
                "limit" => 1,));
        }

        //todo:Remove from $objectsModel the currentObject

		if (!empty($currObjectModel)) {
			$this->render('commonView', array(
				'objectModels' => $objectModels,
				'currentObject' => $currObjectModel,
				'title' => $title,
			));
		} else {
			$this->redirect(array('site/index'));
		}
	}

	public function actionOrganisation() {
		$this->commonLogic('Organisation', 'Organisation');
	}

	public function actionPresentation() {
		$this->commonLogic('Presentation', 'Présentation');
	}

	public function actionActivities() {
		$this->commonLogic('Activity', 'Activités');
	}

	public function actionContact() {
		$contactModel = ContactExtend::model('ContactExtend')->frontEnd()->find();
		if (!empty($contactModel)) {
		$this->render('contact', array(
			'contactModel' => $contactModel,
					));
		} else {
			$this->redirect(array('site/index'));
		}
	}

    public function actionGalleryPhoto() {
        $galleryPhotosModels = GalleryPhotoExtend::model('GalleryPhotoExtend')->frontEnd()->findAll(array(
	        "order" => "t.create_time DESC",
	        'limit' => 5,
	    ));

        if(isset($_GET['id']) && !empty($_GET['id'])){
            $id = $_GET['id'];
            $currphotos = PhotoExtend::model('PhotoExtend')->frontEnd()->findAll(array( "condition" => "t.gallery_photo_id = '".$id."'",));
        } else {
            $currphotos = $models = Yii::app()->db->createCommand()
                ->select('p.name as name ,p.id as id , g.id as gallery_photo_id')
                ->from('photo p')
                ->join('(select id,name from gallery_photo where status = 1  order by create_time DESC limit 1) g', 'g.id=p.gallery_photo_id')
                ->where('p.status=:status', array(':status'=>StatusBehavior::STATUS_ACTIV))
                ->queryAll();
        }

		if (!empty($currphotos)) {
			$cs = Yii::app()->clientScript;
			$cs->registerCoreScript('jquery');
			$cs->registerScript('gallerie', '
				$(".fancy").click(function(){
					var rel = $(this).attr("rel");
					rel = "."+rel;
					$(rel).trigger("click");
					return false;
				});
			', CClientScript::POS_END);
			$this->render('galleryphoto', array(
				'galleryPhotosModels' => $galleryPhotosModels,
				'currphotos'=> $currphotos,
			));
		} else 	{
			$homeModels = HomeExtend::model('HomeExtend')->frontEnd()->findAll();
			$this->render('index', array(
					'homeModels' => $homeModels,
			));
		}
    }

    public function actionGalleryVideo() {
        $galleryVideosModels = GalleryVideoExtend::model('GalleryVideoExtend')->frontEnd()->findAll(array(
	        "order" => "t.create_time DESC",
			'limit' => 5,
        ));

        if(isset($_GET['id']) && !empty($_GET['id'])){
            $id = $_GET['id'];
            $currvideoModel = GalleryVideoExtend::model('GalleryVideoExtend')->frontEnd()->find(array( "condition" => "t.id = '".$id."'",));
        } else {
            $currvideoModel = GalleryVideoExtend::model('GalleryVideoExtend')->frontEnd()->find(array(
                "condition" => "t.status = '".StatusBehavior::STATUS_ACTIV."'",
                "order" => "t.create_time DESC",
                "limit" => 1,));
        }
		
		if (!empty($currvideoModel)) {
			$this->render('galleryvideo', array(
				'videoModels' => $galleryVideosModels,
				'currentvideo' => $currvideoModel,
			));
		} else {
			$homeModels = HomeExtend::model('HomeExtend')->frontEnd()->findAll();
			$this->render('index', array(
					'homeModels' => $homeModels,
			));
		}
    }

    public function actionPoll() {


npsp/protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

npsp/protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

npsp/protected/views/layouts/main-o.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="language" content="fr" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<?php
//Yii::app()->bootstrap->register();
$baseUrl = Yii::app()->baseUrl;
$cs = Yii::app()->getClientScript();

?>
<body class="home">
<div class="container">
<div class="surheader row" style="background-image: url('images/arabesque.png');">
    <div class="col-lg-12">
        <form class="form-email pull-right" method="post">
            <label for="email">Votre email</label>
            <input id="email" name="email" type="text" style="width:150px" class="input-small" placeholder="">
            <button type="submit" class="btn btn-xs">OK</button>
        </form>
    </div>
</div>
<header class="header row" style="min-height: 232px;">
</header>

<nav class="menu row">
    <ul class="list-unstyled col-md-9">
        <li class="<?php if (Yii::app()->controller->getRoute() == "site/index") { echo "active"; } ?> col-sm-2"><a href="<?php echo $this->createUrl('/site/index'); ?>">Accueil</a></li>
        <li class="<?php if (Yii::app()->controller->getRoute() == "site/presentation") { echo "active"; } ?> col-sm-2"><a href="<?php echo $this->createUrl('/site/presentation'); ?>">Présentation</a></li>
        <li class="<?php if (Yii::app()->controller->getRoute() == "site/organisation") { echo "active"; } ?> col-sm-2"><a href="<?php echo $this->createUrl('/site/organisation'); ?>">Organisation</a> </li>
	    <li class="<?php if (Yii::app()->controller->getRoute() == "site/activities") { echo "active"; } ?> col-sm-2"><a href="<?php echo $this->createUrl('/site/activities'); ?>">Activités</a> </li>
        <li class="<?php if (Yii::app()->controller->getRoute() == "site/contact") { echo "active"; } ?> col-sm-2"><a href="<?php echo $this->createUrl('/site/contact'); ?>">Contacts</a></li>
    </ul>
</nav>
    <?php $this->widget('FlashInfoWidget'); ?>
    <?php echo $content; ?>

    <?php $this->widget('PartnerWidget'); ?>


<footer class="footer row">
    <p class="col-md-offset-1 col-md-10">Copyright @ Nouvelle PSP Côte d'ivoire 2014 | tous droits réservés | Administration</p>
</footer>
</div>
</body>
<?php
$cs->registerCoreScript('jquery');
$cs->registerCssFile($baseUrl.'/css/bootstrap.min.css');
$cs->registerCssFile($baseUrl.'/css/app.css');
$cs->registerScriptFile($baseUrl.'/js/bootstrap.min.js');
$cs->registerScriptFile($baseUrl.'/js/app.js');
$cs->registerScriptFile($baseUrl.'/js/j_marquee.js');
?>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-56971301-1', 'auto');
  ga('send', 'pageview');

</script>
</html>

npsp/protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="language" content="fr" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
	<script type="text/javascript">
        window.location = "http://www.npsp.ci/update_navigator.html";
    </script>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>
<?php
//Yii::app()->bootstrap->register();
$baseUrl = Yii::app()->baseUrl;
$cs = Yii::app()->getClientScript();

?>
<body class="home">
<div class="container">
<div class="surheader row" style="background-image: url('../../../images/fond-vert.png');">
    <div class="col-lg-12">
        <div class="pull-left" style="height:30px; width:500px;">
    <a href="https://web.facebook.com/agacameabidjan2018/"><img title="Facebook" src="../images/Facebook.png" height="30" width="30" style="margin-top:2px;" />
    </a>

    <a href="https://www.youtube.com/channel/UCw6yVdfie4gX6fHrsaqOVPA">
    <img title="Youtube" src="../images/Youtube.png" height="30" width="30" style="margin-top:2px;" /></a>

    <a href="https://twitter.com/NouvellePSPCI"> <img title="Tweeter" src="../images/Tweeter.png" height="30" width="30" style="margin-top:2px; margin-right:5px;" />
    </a>
    
   <!--<span style="color:#fff;"> Pour plus d'infos sur l'ACAME </span> <a style="color:#fff;" href="<?php echo Yii::app()->request->baseUrl; ?>/acame">Cliquez ICI</a>-->
    </div>
        
        <form class="form-email pull-right" method="post">
            <label for="email">Votre email</label>
            <input id="email" name="email" type="text" style="width:150px" class="input-small" placeholder="">
            <button type="submit" class="btn btn-xs">OK</button>
        </form>
    </div>
</div>
<header class="header row" style="min-height: 232px;">
</header>

<nav class="menu row">
    <ul class="list-unstyled col-md-12">
        <li class="<?php if (Yii::app()->controller->getRoute() == "site/index") { echo "active"; } ?> col-sm-1"><a href="<?php echo $this->createUrl('/site/index'); ?>">Accueil</a></li>
        <li class="<?php if (Yii::app()->controller->getRoute() == "site/presentation") { echo "active"; } ?> col-sm-1"><a href="<?php echo $this->createUrl('/site/presentation'); ?>">Présentation</a></li>
        <li class="<?php if (Yii::app()->controller->getRoute() == "site/organisation") { echo "active"; } ?> col-sm-2"><a href="<?php echo $this->createUrl('/site/organisation'); ?>">Organisation</a> </li>
	    <li class="<?php if (Yii::app()->controller->getRoute() == "site/activities") { echo "active"; } ?> col-sm-1"><a href="<?php echo $this->createUrl('/site/activities'); ?>">Activités</a> </li>
	     <li class="<?php if (Yii::app()->controller->getRoute() == "site/") { echo "active"; } ?> col-sm-2"><a href="../images/index_pharmaceutique_npsp.pdf" target="blank">Liste produits<img src="../images/new-icon.gif" width="30"></a> </li>
        <li class="<?php if (Yii::app()->controller->getRoute() == "site/contact") { echo "active"; } ?> col-sm-2"><a href="<?php echo $this->createUrl('/site/contact'); ?>">Nous écrire</a></li>
        
         <li class="col-sm-1"><a href="<?php echo Yii::app()->request->baseUrl; ?>/Espace_client/veille.com/">Veille</a></li>
        
         <li class="<?php if (Yii::app()->controller->getRoute() == "site/site") { echo "active"; } ?> col-sm-2"><a href="<?php echo $this->createUrl('../Espace_client/loginEC.php'); ?>">Espace Client</a></li>
    </ul>
</nav>
    <?php $this->widget('FlashInfoWidget'); ?>
    <?php echo $content; ?>

    <?php $this->widget('PartnerWidget'); ?>


<footer class="footer row">

	<div class="lien_utile" style="width:100%; height:auto; padding-left:10px; padding-right:10px; padding-top:10px; padding-bottom:10px"><center>
	<div style="clear:both"></div>
    <h4 align="center">----------------------------------------------Liens utiles----------------------------------------</h4>
    	<div style=" float:left; display:block; color:#030; font-size:12px; width:auto; height:17px; padding:3px; margin-left:5px; margin-top:5px"><a href="http://www.insp-ci.org" target="_blank">INSTITUT NATIONAL DE LA SANTE PUBLIQUE |</a></div>
        	<div style=" float:left; display:block; color:#030; font-size:12px; width:auto; height:17px; padding:3px; margin-left:5px ; margin-top:5px"><a href="http://www.cnts-ci.org" target="_blank">CENTRE NATIONAL DE TRANSFUSION SANGUINE |</a></div>
            <div style=" float:left; display:block; color:#030; font-size:12px; width:auto; height:17px; padding:3px; margin-left:5px; margin-top:5px" ><a href="http://www.cardiologie.gouv.ci" target="_blank">INSTITUT DE CARDIOLOGIE D'ABIDJAN |</a></div>
            <div style=" float:left; display:block; color:#030; font-size:12px; width:auto; height:17px; padding:3px; margin-left:5px; margin-top:5px"><a href="http://www.inhp.ci" target="_blank">INSTITUT NATIONAL D'HYGIENE PUBLIQUE</a></div>
            <div style=" float:left; display:block; color:#030; font-size:12px; width:auto;  height:17px;padding:3px; margin-left:5px; margin-top:5px"><a href="http://www.pasteur.ci" target="_blank">INSTITUT PASTEUR COTE D'IVOIRE |</a></div>
            <div style=" float:left; display:block; color:#030; font-size:12px; width:auto;  height:17px;padding:3px; margin-left:5px; margin-top:5px"><a href="http://www.samu-ci.com" target="_blank">SAMU |</a></div>
            <div style=" float:left; display:block; color:#030; font-size:12px; width:auto; height:17px; padding:3px; margin-left:5px; margin-top:5px"><a href="http://www.activitepharma-ci.org" target="_blank">PROGRAMME NATIONAL DE DEVELOPPEMENT DE LACTIVITE PHARMACEUTIQUE (PNDAP) |</a></div>
            <div style=" float:left; display:block; color:#030; font-size:12px; width:auto; padding:3px; margin-left:5px; margin-top:5px"><a href="http://www.dphm.ci" target="_blank">DIRECTION DE LA PHARMACIE ET DU MEDICAMENT (DPM) |</a></div>
            <div style=" float:left; display:block; color:#030; font-size:12px; width:auto; height:17px; padding:3px; margin-left:5px; margin-top:5px"><a href="http://www.ordrepharmacien.ci" target="_blank">CONSEIL NATIONAL DE LORDRE DES PHARMACIENS DE COTE DIVOIRE (CNOP-CI) |</a></div>
            <div style=" float:left; display:block; color:#030; font-size:12px; width:auto; height:17px; padding:3px; margin-left:5px; margin-top:5px"><a href="http://www.who.int" target="_blank">ORGANISATION MONDIALE DE LA SANTE (OMS) |</a></div>
                <div style=" float:left; display:block; color:#030; font-size:12px; width:auto; height:17px; padding:3px; margin-left:5px; margin-top:5px"><a href="http://www.synacassci.net" target="_blank">SYNACASS-CI |</a></div>
                <div style=" float:left; color:#030; font-size:12px; width:auto; height:17px; padding:3px; margin-left:5px; margin-top:5px"><a href="http://www.univ-fhb.edu.ci" target="_blank">UFR SCIENCES MEDICALES |</a></div>
                    <div style=" float:left; display:block; color:#030; font-size:12px; width:auto; height:17px; padding:3px; margin-left:5px; margin-top:5px"><a href="http://www.univ-fhb.edu.ci" target="_blank">UFR SCIENCES PHARMACEUTIQUES ET BIOLOGIQUES |</a></div>
                        
                                        <div style=" float:left; color:#030; font-size:12px; width:auto; height:17px; padding:3px; margin-left:5px; margin-top:5px"><a href="http://www.wahooas.org" target="_blank">ORGANISATION OUEST AFRICAINE DE LA SANTE (OOAS) |</a></div>
        
        <div style=" float:left; color:#030; font-size:12px; width:auto; height:17px; padding:3px; margin-left:5px; margin-top:5px"><a href="http://www.medecins.ci/ " target="_blank">ORDRE NATIONAL DES MEDCINS|</a></div>
        
        <div style=" float:left; color:#030; font-size:12px; width:auto; height:17px; padding:3px; margin-left:5px; margin-top:5px"><a href="http://www.ordrechirurgiens-dentistes.ci/" target="_blank">ORDRE NATIONAL DES CHIRURGIENS-DENTISTES DE CÔTE D'IVOIRE</a></div>
        
        
  </center>
    <div style="clear:both"></div>
</div>
    <p class="col-md-offset-1 col-md-10">Copyright @ Nouvelle PSP Côte d'ivoire 2014 | tous droits réservés | Administration</p>
</footer>
</div>
</body>
<?php
$cs->registerCoreScript('jquery');
$cs->registerCssFile($baseUrl.'/css/bootstrap.min.css');
$cs->registerCssFile($baseUrl.'/css/app.css');
$cs->registerScriptFile($baseUrl.'/js/bootstrap.min.js');
$cs->registerScriptFile($baseUrl.'/js/app.js');
$cs->registerScriptFile($baseUrl.'/js/j_marquee.js');
?>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-56971301-1', 'auto');
  ga('send', 'pageview');

</script>
</html>